version: '3.8'

services:
  frontend:
    image: "ghcr.io/karthi209/ones-and-zeros/frontend:${FRONTEND_VERSION}"
    build:
      context: .  # Adjust to the folder containing your React Dockerfile
    ports:
      - "5173:5173"  # React app runs on port 3000 internally, adjust as needed
    depends_on:
      - backend

  backend:
    image: "ghcr.io/karthi209/ones-and-zeros/backend:${BACKEND_VERSION}"
    build:
      context: ./backend/core  # Adjust to the folder containing your Node.js Dockerfile
    ports:
      - "3000:3000"  # Node backend runs on port 5000 internally
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  # PostgreSQL runs on port 5432
    volumes:
      - "/home/karthi209/postgres_data:/var/lib/postgresql/data"

  nginx:
    image: nginx:latest
    volumes:
      - "/home/karthi209/nginx-config/nginx.conf:/etc/nginx/nginx.conf"  # Ensure this path is correct
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
